---
title: "02_validator_from_chain_data"
author: "Chin-Cheng Liang"
date: "3/18/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = FALSE,
    warning=FALSE,
    message=FALSE,
    comment = FALSE)
```


```{r }
library(jsonlite)
library(dplyr)
library(lubridate)
library(ggplot2)

```

Reproduce data and repo: https://github.com/ChihChengLiang/testnet-data-dump


```{r}
epoch_info <- stream_in(file("data/epoch.json"), verbose = FALSE)
```



```{r}
df_clean <- epoch_info %>% jsonlite::flatten() %>% mutate(timestamp = as_datetime(timestamp))

```

If validators are voting smoothly, last finalized epoch should stick very close to current epoch.

Pyethapp miners are not producing blocks well. The join of Harmony miners makes the epochs grow in a rate they should.

```{r}
df_clean %>% ggplot(aes(x=timestamp)) +
    geom_line(aes(y=current_epoch, color="Current Epoch")) +
    geom_line(aes(y=lfe, color="Last Finalied Epoch")) +
    scale_x_datetime(date_labels = "%b-%Y")+
    ylab("Epoch") +
    ggtitle("Current Epoch & Last Finalized Epoch")
```



```{r}
df_clean %>% ggplot(aes(x=timestamp)) +
    geom_line(aes(y=votes.cur_deposits)) +
    scale_x_datetime(date_labels = "%b-%Y") + 
    ggtitle("Total Deposits")
```


```{r}
df_clean %>%
    ggplot(aes(x=timestamp)) +
    geom_line(aes(y=deposit_scale_factor)) +
    scale_x_datetime(date_labels = "%b-%Y") +
    ggtitle("Deposit scale factor")
```


Deposit scale factor drops fast in March


```{r}

df_clean %>% filter(timestamp> as.Date("2018-03-01")) %>% 
    ggplot(aes(x=timestamp)) +
    geom_line(aes(y=deposit_scale_factor)) +
    scale_x_datetime(date_labels = "%d-%b-%Y") +
    scale_y_log10() +
    ggtitle("Deposit scale factor in log scale")

```

```{r}

df_clean %>%
    ggplot(aes(x=timestamp)) +
    geom_line(aes(y=votes.last_nonvoter_rescale, color="Last Non-voter Rescale")) +
    geom_line(aes(y=votes.last_voter_rescale, color="Last voter Rescale")) +
    scale_x_datetime(date_labels = "%b-%Y") +
    ggtitle("Last Voter/Non-Voter Rescale")

```


```{r}
df_clean %>%
    filter(timestamp>as.Date("2018-01-01")) %>%
    ggplot(aes(x=timestamp)) +
    geom_line(aes(y=votes.last_nonvoter_rescale, color="Last Non-voter Rescale")) +
    geom_line(aes(y=votes.last_voter_rescale, color="Last voter Rescale")) +
    scale_x_datetime(date_labels = "%b-%Y") +
    ggtitle("Last Voter/Non-Voter Rescale: Close up")
```

```{r}
df_clean %>% ggplot(aes(x=timestamp)) +
    geom_line(aes(y=storage)) +
    scale_x_datetime(date_labels = "%b-%Y") +
    ggtitle("Casper Contract Account Storage Usage")
```

